[package]
name = "egor00f/preloadlib"

description = "library for automaticly preload content"

version = "0.1.0"

registry = "https://github.com/UpliftGames/wally-index"

# or server
realm = "shared"

license = "MIT"

repository = "https://github.com/Ukuroks-games/PreloadLib"

authors = ["Egor00f <velikiydolbayeb@gmail.com>"]

exclude = ["*"]

include = [
	"src",
	"src/**",
	"wally.toml",
	"README.md",
	"init.lua"
]

private = false

[dependencies]
switch = "egor00f/switch@0.1.1"

[server-dependencies]


[dev-dependencies]

